name: docs

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']

    steps:
    # Remains to be sorted.
      - uses: actions/checkout@v3
      - name: install non-python dependencies
        run: sudo apt-get install -y pandoc graphviz
      - name: Install poetry
        run: pipx install poetry
        with: 
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install
      - name: Docs
        run: |
          cd docs && poetry run sphinx-build -b html -E source ../gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: gh-pages

