name: testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.4"
          cache: poetry

      - name: Install poetry
        run: pipx install poetry

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install project
        run: |
          poetry env use "3.10.4"
          poetry install

      - name: Install FragGeneScanRs
        run: cargo install frag_gene_scan_rs

      - name: Run tests
        run: poetry run pytest -v -s -o faulthandler_timeout=60